build: Try default of eliminating use of glibc dep

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -34,17 +34,17 @@ export VERSION ||
 		printf '%s\n' "Error: export failure."
 		exit 1
 	}
-export LDFLAGS='-X main.VERSION='${VERSION:?Error: VERSION undefined.}' -s -w -linkmode "external" -extldflags "-static"' ||
+export LDFLAGS='-X main.VERSION='${VERSION:?Error: VERSION undefined.}' -s -w -linkmode "internal" -buildid=' ||
 	{
 		printf '%s\n' "Error: export failure."
 		exit 1
 	}
-CGO_ENABLED=1 go build -v -a -ldflags "${LDFLAGS:?Error: LDFLAGS undefined.}" -o "client_gfcp_${VERSION:?Error: VERSION undefined.}" ../client ||
+CGO_ENABLED=0 go build -tags="osnetgo,osusergo" -v -a -ldflags "${LDFLAGS:?Error: LDFLAGS undefined.}" -o "client_gfcp_${VERSION:?Error: VERSION undefined.}" ../client ||
 	{
 		printf '%s\n' "Error: Client build failed."
 		exit 1
 	}
-CGO_ENABLED=1 go build -v -a -ldflags "${LDFLAGS:?Error: LDFLAGS undefined.}" -o "server_gfcp_${VERSION:?Error: VERSION undefined.}" ../server ||
+CGO_ENABLED=0 go build -tags="osnetgo,osusergo" -v -a -ldflags "${LDFLAGS:?Error: LDFLAGS undefined.}" -o "server_gfcp_${VERSION:?Error: VERSION undefined.}" ../server ||
 	{
 		printf '%s\n' "Error: Server build failed."
 		exit 1
