compile: Warn when missing UPX, detect UPX failure

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -49,10 +49,16 @@ CGO_ENABLED=0 go build -tags="osnetgo,osusergo" -v -a -ldflags "${LDFLAGS:?Error
 		printf '%s\n' "Error: Server build failed."
 		exit 1
 	}
-UPXC=$(env command -v upx 2>/dev/null || printf '%s' "true") || true
-if [ ! -z "${UPXC:-}" ]; then
-	printf '%s\n' "Compressing output."
-	strip --strip-all ./*_gfcp_*-gridfinity && ${UPXC:-} --ultra-brute -qq ./*_gfcp_*-gridfinity
-	printf '%s\n' "Compression completed."
+UPXC=$(env command -v upx 2>/dev/null || printf '%s' "true") || true :
+# shellcheck disable=SC2236,SC2154
+if [ ! -z "${UPXC:-}" ] || [ -n "${UPXC:-}" ]; then
+	printf '%s\n' "Compressing output with UPX, please wait ..."
+	# shellcheck disable=SC2015
+	strip --strip-all ./*_gfcp_*-gridfinity &&
+		"${UPXC:-}" "--ultra-brute" "-qq" ./*_gfcp_*-gridfinity &&
+		printf '%s\n' "UPX compression completed successfully." ||
+		{ printf '%s\n' "Error: UPX compression failure."; }
+else
+	printf '%s\n' "UPX not available, skipping binary compression."
 fi
 printf '%s\n' "Build completed."
